# Create Kubernetes, Containerd, and CNI persistent state directories in /var on boot
# Format: Type Path Mode User Group Age Argument
d /var/lib/kubelet 0755 root root - -
d /var/lib/containerd 0755 root root - -
d /var/lib/cni 0755 root root - -

# Create Open-iSCSI persistent directories in /var on boot (required for democratic-csi block mounts)
d /var/lib/iscsi 0755 root root - -
d /var/lib/iscsi/ifaces 0755 root root - -
d /var/lib/iscsi/isns 0755 root root - -
d /var/lib/iscsi/nodes 0750 root root - -
d /var/lib/iscsi/send_targets 0750 root root - -
d /var/lib/iscsi/static 0750 root root - -
