# Create Kubernetes and Containerd persistent state directories in /var on boot
# Format: Type Path Mode User Group Age Argument
d /var/lib/kubelet 0755 root root - -
d /var/lib/containerd 0755 root root - -
d /var/lib/cni 0755 root root - -
